In [1]:
# Import the modules
from pathlib import Path
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt

In [2]:
# Read the  file from folder into a Pandas DataFrame
data = Path('mejorsabor.xlsx')
df = pd.read_excel(data)


# Review the DataFrame
df.head()

,Country - Country from URL.,D1 - Are you?,D3 - What is the number of inhabitants of the city in which you live?,D5 - What is the gross (average) annual income of your household?,What is the gross (average) annual income of your household per head,D4 - How old are you?,D5 - What is the gross (average) annual income of your household?.1,D7 - What is the highest level of education you have achieved?,"D9 - How many people are in your household (including adults, children and yourself)?",D9a - Played video games,D9a - Bought a grand piano,D9a - Participated in team sports classes,D9a - Working out in a gym,D9a - Dine in a restaurant,D9a - Founded a charity,D9a - Making Online Purchases,D9a - None of these answers,PG5 - Do you feel you have enough information about the nutritional quality and environmental/social respect of the products you buy?,PP3 - Better taste
0,France||FR,Un homme,10 000 à 49 999 habitants,64999.5,12999.900,59,60 000 € à 69 999 €,Bac+5,5,0,0,0,1,1,0,1,0,"Oui, partiellement",5% plus cher
1,France||FR,Une femme,10 000 à 49 999 habitants,10000.0,10000.000,64,Moins de 20 000 €,Bac,1,0,0,0,1,1,0,1,0,"Oui, partiellement","Non, même prix"
2,France||FR,Un homme,5 000 à 9 999 habitants,24999.5,6249.875,50,20 000 € à 29 999 €,Bac+2/Bac+3,4,1,0,0,0,1,0,1,0,"Oui, partiellement",5% plus cher
3,France||FR,Un homme,10 000 à 49 999 habitants,24999.5,24999.500,30,20 000 € à 29 999 €,Bac+2/Bac+3,1,1,0,0,0,1,0,1,0,"Oui, tout à fait",5% plus cher
4,France||FR,Une femme,10 000 à 49 999 habitants,10000.0,5000.000,48,Moins de 20 000 €,Bac,2,1,0,0,0,0,0,1,0,"Oui, partiellement","Non, même prix"

In [3]:
# List of columns to delete
columns_to_delete = ["D9a - None of these answers", "D5 - What is the gross (average) annual income of your household?.1"]

# Use the drop() method to delete the specified columns and create a new DataFrame without them
df = df.drop(columns=columns_to_delete)

# Display the DataFrame after deleting the columns
df.head()

,Country - Country from URL.,D1 - Are you?,D3 - What is the number of inhabitants of the city in which you live?,D5 - What is the gross (average) annual income of your household?,What is the gross (average) annual income of your household per head,D4 - How old are you?,D7 - What is the highest level of education you have achieved?,"D9 - How many people are in your household (including adults, children and yourself)?",D9a - Played video games,D9a - Bought a grand piano,D9a - Participated in team sports classes,D9a - Working out in a gym,D9a - Dine in a restaurant,D9a - Founded a charity,D9a - Making Online Purchases,PG5 - Do you feel you have enough information about the nutritional quality and environmental/social respect of the products you buy?,PP3 - Better taste
0,France||FR,Un homme,10 000 à 49 999 habitants,64999.5,12999.900,59,Bac+5,5,0,0,0,1,1,0,1,"Oui, partiellement",5% plus cher
1,France||FR,Une femme,10 000 à 49 999 habitants,10000.0,10000.000,64,Bac,1,0,0,0,1,1,0,1,"Oui, partiellement","Non, même prix"
2,France||FR,Un homme,5 000 à 9 999 habitants,24999.5,6249.875,50,Bac+2/Bac+3,4,1,0,0,0,1,0,1,"Oui, partiellement",5% plus cher
3,France||FR,Un homme,10 000 à 49 999 habitants,24999.5,24999.500,30,Bac+2/Bac+3,1,1,0,0,0,1,0,1,"Oui, tout à fait",5% plus cher
4,France||FR,Une femme,10 000 à 49 999 habitants,10000.0,5000.000,48,Bac,2,1,0,0,0,0,0,1,"Oui, partiellement","Non, même prix"

In [4]:
# Define a dictionary that maps the current column names to the new column names
column_mapping = {
    'Country - Country from URL.': 'Country',
    'D1 - Are you?': 'Gender',
    'D3 - What is the number of inhabitants of the city in which you live?': 'population',
    'D5 - What is the gross (average) annual income of your household?': 'Income',
    'What is the gross (average) annual income of your household per head': 'incomepc',
    'D4 - How old are you?': 'Age',
    'D7 - What is the highest level of education you have achieved?': 'Education',
    'D9 - How many people are in your household (including adults, children and yourself)?': 'pc',
    'D9a - Played video games': 'Videogames',
    'D9a - Bought a grand piano': 'Piano',
    'D9a - Participated in team sports classes': 'Teamsport',
    'D9a - Working out in a gym': 'gym',
    'D9a - Dine in a restaurant': 'Restaurant',
    'D9a - Founded a charity': 'Charity',
    'D9a - Making Online Purchases': 'Ecommerce',
    'PG5 - Do you feel you have enough information about the nutritional quality and environmental/social respect of the products you buy?': 'Information',
    'PP3 - Better taste': 'taste'
}

# Use the rename() method to change the column names
df = df.rename(columns=column_mapping)

# Display the DataFrame with the new column names
df.head()

,Country,Gender,population,Income,incomepc,Age,Education,pc,Videogames,Piano,Teamsport,gym,Restaurant,Charity,Ecommerce,Information,taste
0,France||FR,Un homme,10 000 à 49 999 habitants,64999.5,12999.900,59,Bac+5,5,0,0,0,1,1,0,1,"Oui, partiellement",5% plus cher
1,France||FR,Une femme,10 000 à 49 999 habitants,10000.0,10000.000,64,Bac,1,0,0,0,1,1,0,1,"Oui, partiellement","Non, même prix"
2,France||FR,Un homme,5 000 à 9 999 habitants,24999.5,6249.875,50,Bac+2/Bac+3,4,1,0,0,0,1,0,1,"Oui, partiellement",5% plus cher
3,France||FR,Un homme,10 000 à 49 999 habitants,24999.5,24999.500,30,Bac+2/Bac+3,1,1,0,0,0,1,0,1,"Oui, tout à fait",5% plus cher
4,France||FR,Une femme,10 000 à 49 999 habitants,10000.0,5000.000,48,Bac,2,1,0,0,0,0,0,1,"Oui, partiellement","Non, même prix"

In [5]:
# Confirm the unique values from PP3 - Better taste
unique_values = df['taste'].unique()
print(unique_values)

['5% plus cher' 'Non, même prix' '10% plus cher' '20% plus cher']

In [ ]:
# Create a dictionary to map the textual values to numerical values
replace_dict = {
    '5% plus cher': 5,
    'Non, même prix': 0,
    '10% plus cher': 10,
    '20% plus cher': 20
}

# Use the replace() method to replace the values in the column
df['taste'] = df['taste'].replace(replace_dict)

# Review the DataFrame
df.head()

In [ ]:
# Confirm the unique values from population
unique_values = df['population'].unique()
print(unique_values)

In [ ]:
# Create a dictionary to map the textual values to numerical values
replace_dict = {
    'Moins de 2 000 habitants': 1000,
    '2 000 à 4 999 habitants': 3500,
    '5 000 à 9 999 habitants': 7500,
    '10 000 à 49 999 habitants': 30000,
    '50 000 à 99 999 habitants': 75000,
    '100 000 à 499 999 habitants': 30000,
    '500 000 à 999 999 habitants': 750000,
    '1 million et plus d’habitants': 1000000
    
}

# Use the replace() method to replace the values in the column
df['population'] = df['population'].replace(replace_dict)

# Review the DataFrame
df.head()

In [ ]:
# # Confirm the unique values from Education
# unique_values = df['Education'].unique()
# print(unique_values)

In [ ]:
# # Create a dictionary to map the textual values to numerical values
# replace_dict = {
#     'Collège': 7,
#     'Bac': 8,
#     'Bac+2/Bac+3': 10,
#     'Bac+5': 12,
#     'Doctorat': 14
# }

# # Use the replace() method to replace the values in the column
# df['Education'] = df['Education'].replace(replace_dict)

# # Review the DataFrame
# df.head()

In [ ]:
# Confirm the unique values from Country
unique_values = df['Country'].unique()
print(unique_values)

In [ ]:

replace_dict = {
    'France||FR': 'FR',
    'UK||GB':'UK',
    'Germany||DE': 'DE',
    'Spain||ES': 'ES'
}

# Use the replace() method to replace the values in the column
df['Country'] = df['Country'].replace(replace_dict)

# Review the DataFrame
df.head()

In [ ]:
# # Confirm the unique values from Information
# unique_values = df['Information'].unique()
# print(unique_values)

In [ ]:

# replace_dict = {
#     'Non, pas du tout': 0,
#     'Oui, partiellement': 1,
#     'Oui, tout à fait': 2
# }

# # Use the replace() method to replace the values in the column
# df['Information'] = df['Information'].replace(replace_dict)

# # Review the DataFrame
# df.head()

In [ ]:
# Confirm the unique values from Gender
unique_values = df['Gender'].unique()
print(unique_values)

In [ ]:

replace_dict = {
    'Un homme': 1,
    'Une femme': 0
}

# Use the replace() method to replace the values in the column
df['Gender'] = df['Gender'].replace(replace_dict)

# Review the DataFrame
df.head()

In [ ]:
# Deleting the missing values, given the low number of them, this change will not affect the results significantly, so our models will work seamlessly.
df =  df.dropna()
# Review the DataFrame
df.head()

In [ ]:
result = df.groupby('taste').count()

print(result)

In [ ]:
# Count the number of NaN values per column
nan_counts = df.head().isna().sum()

# Display the number of NaN values per column
print(nan_counts)

In [ ]:
# Import the StandardScaler from scikit-learn
from sklearn.preprocessing import StandardScaler

# Create a DataFrame with the scaled data for selected columns
df_scaled = df[["population", "Income", "incomepc", "Age", "pc"]].copy()

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit and transform the selected columns
df_scaled[["population", "Income", "incomepc", "Age", "pc"]] = scaler.fit_transform(df[["population", "Income", "incomepc", "Age", "pc"]])

# Copy the remaining columns to df_scaled
df_scaled[["Country", "Gender", "Videogames", "Piano", "Teamsport", "gym", "Restaurant", "Charity", "Ecommerce", "Information", "taste","Education"]] = df[["Country", "Gender", "Videogames", "Piano", "Teamsport", "gym", "Restaurant", "Charity", "Ecommerce", "Information", "taste","Education"]]

# Define the desired column order
column_order = [
    "Country", "Gender", "population", "Income", "incomepc", "Age", "Education", "pc",
    "Videogames", "Piano", "Teamsport", "gym", "Restaurant", "Charity", "Ecommerce", "Information", "taste"
]

# Reorder the columns in the DataFrame
df_scaled = df_scaled[column_order]

# Display the DataFrame with the reordered columns and scaled values
df_scaled.head()

In [ ]:
# # Count the number of NaN values per column
# nan_counts = df_scaled.isna().sum()

# # Display the number of NaN values per column
# print(nan_counts)


df_scaled.columns

In [ ]:
# Specify the columns to convert to dummies
# columns_to_dummies = ["Country","Gender","Videogames","Piano","Teamsport","gym","Restaurant","Charity","Ecommerce","Information" ]
columns_to_dummies = ["Country", "Education","Information"]

# Convert categorical data to numeric with pd.get_dummies
df_scaled = pd.get_dummies(df_scaled, columns=columns_to_dummies)
df_scaled.head()

In [ ]:
# CLUSTER

from sklearn.cluster import KMeans

# Create a list with the number of k-values from 1 to 11
k = list(range(1, 11))

# Create an empty list to store the inertia values
inertia = []

# Create a for loop to compute the inertia with each possible value of k
# Inside the loop:
# 1. Exclude the "taste" column from df_scaled (assuming it's a Pandas DataFrame).
# 2. Create a KMeans model using the loop counter for the n_clusters.
# 3. Fit the model to the data without the "taste" column.
# 4. Append the model.inertia_ to the inertia list.
for i in k:
    # Exclude the "taste" column from df_scaled
    df_cluster_data = df_scaled.drop(columns=["taste"])
    
    k_model = KMeans(n_clusters=i, random_state=1)
    k_model.fit(df_cluster_data)
    inertia.append(k_model.inertia_)

# Create a dictionary with the data to plot the Elbow curve
elbow_data = {"k": k, "inertia": inertia}
df_elbow1 = pd.DataFrame(elbow_data)

# Plot a line chart with all the inertia values computed with 
# the different values of k to visually identify the optimal value for k.
import matplotlib.pyplot as plt

plt.plot(df_elbow1["k"], df_elbow1["inertia"])
plt.title("Elbow Curve")
plt.xlabel("k")
plt.ylabel("Inertia")
plt.xticks(k)
plt.show()

In [ ]:
# cLUSTER
# This part was added to double check if adding clusters of the type of clients would increase the explanatory power of the models
# After a review of the performance of the model with and without the clusterirazion, we concluded that this actually decreased the accuracy of our models, so we deleted this variable from the models



# Assuming df_scaled contains the scaled data

# Initialize the K-Means model using the best value for k
model = KMeans(n_clusters=4, random_state=1)

# Fit the K-Means model using the scaled data
model.fit(df_cluster_data)

# Predict the clusters to group the cryptocurrencies using the scaled data
segments = model.predict(df_cluster_data)

# Convert the segments array into a DataFrame
segments_df = pd.DataFrame(segments, columns=['segments'])

# Create a copy of the scaled DataFrame
df_cluster_data = df_cluster_data.copy()

# Add a new column to the DataFrame with the predicted clusters
df_cluster_data['segments'] = segments_df

# Display sample data
df_cluster_data.head()
df_cluster_data.columns

In [ ]:
# cLUSTER
# Count the number of NaN values per column
nan_counts = df_cluster_data.isna().sum()

# Display the number of NaN values per column
print(nan_counts)

In [ ]:
df_cluster_data.head()

In [ ]:
# cLUSTER
df['segments'] = df_cluster_data['segments']

result = df.groupby('segments').count()

print(result)

In [ ]:
df.head()

result = df.groupby('segments').mean()

print(result)

In [ ]:
# cLUSTER
df_scaled['segments'] = df_cluster_data['segments']
df_scaled.head()

In [ ]:
# Count the number of NaN values per column
nan_counts = df_scaled.isna().sum()

# Display the number of NaN values per column
print(nan_counts)

# df_scaled.head()

In [ ]:
# Separate the y variable, the labels without the segments variables
y = df_scaled["taste"]
# Separate the X variable, the features
X = df_scaled.drop(columns="taste")

In [ ]:
# Import the train_test_split module
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
# Assign a random_state of 1 to the function
# Specify stratify=y to ensure stratified sampling based on y
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

# Check the shape of X_train
X_train.shape

In [ ]:
# Now we will try to do a over sampler to confirm if this can increase the performance of the model.

# Import the RandomOverSampler module form imbalanced-learn
from imblearn.over_sampling import RandomOverSampler

# Instantiate the random oversampler model
# # Assign a random_state parameter of 1 to the model
ros = RandomOverSampler(random_state=1)

# Fit the original training data to the random_oversampler model
X_train_resampled, y_train_resampled = ros.fit_resample(X_train, y_train)

In [ ]:
# Count the distinct values of the resampled labels data
label_counts = pd.Series(y_train_resampled).value_counts()

print(label_counts)

In [ ]:
# Create a random forest classifier
rf_model = RandomForestClassifier(n_estimators=5000, random_state=1)

In [ ]:
# Fitting the model
rf_model.fit(X_train_resampled, y_train_resampled)

In [ ]:
# Making predictions using the testing data
predictions = rf_model.predict(X_test)

In [ ]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, predictions)

# Define custom labels for actual and predicted values
labels = [0, 5, 10, 20]

# Create a DataFrame with custom labels for both actual and predicted values
cm_df = pd.DataFrame(cm, index=labels, columns=labels)

# Add labels for both actual and predicted values
cm_df.index.name = 'Actual'
cm_df.columns.name = 'Predicted'

# Calculating the accuracy score
acc_score = accuracy_score(y_test, predictions)

In [ ]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

In [ ]:
# Random Forests in sklearn will automatically calculate feature importance
importances = rf_model.feature_importances_

# We can sort the features by their importance
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt  # Add this import statement

# Random Forests in sklearn will automatically calculate feature importance
importances = rf_model.feature_importances_

# We can sort the features by their importance
feature_names = X.columns  # Assuming X is your feature matrix

# Sort feature importances in descending order
indices = np.argsort(importances)[::-1]

# Plot the feature importances
plt.figure(figsize=(10, 6))
plt.title("Feature Importances")
plt.bar(range(X.shape[1]), importances[indices], align="center")
plt.xticks(range(X.shape[1]), [feature_names[i] for i in indices], rotation=90)
plt.tight_layout()
plt.show()

In [ ]:
# Separate the y variable, the labels without the "taste" column
y = df_scaled["taste"]
# Separate the X variable, the features
X = df_scaled.drop(columns="taste")

# Import necessary libraries
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder  # Import the LabelEncoder

# Split the data using train_test_split
# Assign a random_state of 1 to the function
# Specify stratify=y to ensure stratified sampling based on y
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

# Initialize the LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform the "taste" values in y_train
y_train_encoded = label_encoder.fit_transform(y_train)

# Create an XGBoost classifier
xgb_model = xgb.XGBClassifier()

# Fitting the model with the encoded target variable
xgb_model.fit(X_train, y_train_encoded)

# Making predictions using the testing data
predictions_encoded = xgb_model.predict(X_test)

# Inverse transform the predictions to get the original values
predictions = label_encoder.inverse_transform(predictions_encoded)

# Calculating the confusion matrix
cm = confusion_matrix(y_test, predictions)

# Define custom labels for actual and predicted values
labels = df_scaled["taste"].unique()

# Create a DataFrame with custom labels for both actual and predicted values
cm_df = pd.DataFrame(cm, index=labels, columns=labels)

# Add labels for both actual and predicted values
cm_df.index.name = 'Actual'
cm_df.columns.name = 'Predicted'

# Calculating the accuracy score
acc_score = accuracy_score(y_test, predictions)

# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score: {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))